version: "3.7"
services:
  app:
    image: jekyll/jekyll:3
    command: jekyll serve --watch --drafts
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  sample_1:
    image: php:7.2-apache
    volumes:
      - ./samples/1/:/var/www/html
    ports:
      - "4001:80"
